### ISSUE TITLE
Plugin disabled in Grafana 8 due to missing signature

### ISSUE THREAD

**Issue by gitgia** [thiagoarrais/grafana-matomo-tracking-panel#9]
Hi,
the matomo plugin ist disabled in Grafana 8, because of the missing signature, can you do something  about it?
There is a manual from Grafana, how to [sign a plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/)

Thanks!
![image](https://user-images.githubusercontent.com/41324844/121675659-fac36c00-cab3-11eb-907c-f43a4f85075a.png)

**Comment by Shabinder** [comment]
+1

**Comment by thiagoarrais** [comment]
I'll have look. Thanks for the heads up!

**Comment by thiagoarrais** [comment]
Version 0.2.3 is ready with signature and other fixes. Please add your thumbs up to the marketplace PR (above) to help the Grafana team gauge interest in this.

**Comment by gitgia** [comment]
Done. Thanks again!

**Comment by thiagoarrais** [comment]
The Grafana marketplace team finished publishing the new version. This should be fixed now. Can you confirm and close the issue if appropriate, @gitgia ?

**Comment by thiagoarrais** [comment]
Closing this since It Works On My Machine (tm). Please reopen if needed.
